name: iOS CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CocoaPods
        run: |
          pod install

      - name: Show available simulators
        run: |
          xcrun simctl list devices

      - name: Build app
        run: |
          xcodebuild clean build \
          -workspace NasiShadchanHelper.xcworkspace \
          -scheme NasiShadchanHelper \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_ALLOWED=NO

      - name: Run unit tests
        run: |
          xcodebuild test \
          -workspace NasiShadchanHelper.xcworkspace \
          -scheme NasiShadchanHelper \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          CODE_SIGNING_ALLOWED=NO
